# File: v3io_tsdb_config.yaml

# NGINX server address:PORT
webApiEndpoint: "10.10.10.10:8081"

# V3IO container ID or Name
container: "bigdata"

# Table path in the container
tablePath: "tsdb1"


# Logging level. Valid values: debug,info,warn,error (Default: info)
verbose: "info"

# Authentication for nginx
username: "iguazio"
password: "password"

# Num of workers for handling the REST requests to nginx
workers: 100

batchSize: 10000

# Timeout for nginx requests
#timeout: 10

performance:
  reportOnShutdown: false
  output: "stdout"
  reportPeriodically: false
  reportInterval: 10
